# 📘 Notebook — Comparativa Completa dels Models Naive Bayes (scikit-learn)
Aquest notebook compara **GaussianNB**, **MultinomialNB**, **BernoulliNB** i **CategoricalNB**
amb exemples simples i representatius per estudiants de FP.

## 🟦 1. GaussianNB — Dades contínues
Aquest model assumeix que cada característica segueix una distribució normal.

In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB, CategoricalNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Dataset contínu
np.random.seed(0)
X_cont = np.vstack([
    np.random.normal(0,1,(100,2)),  # classe 0
    np.random.normal(4,1,(100,2))   # classe 1
])
y_cont = np.array([0]*100 + [1]*100)

X_train, X_test, y_train, y_test = train_test_split(X_cont, y_cont, test_size=0.3, random_state=42)

g_model = GaussianNB()
g_model.fit(X_train, y_train)
y_pred = g_model.predict(X_test)
print('== GaussianNB ==')
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

== GaussianNB ==
[[31  0]
 [ 0 29]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        31
           1       1.00      1.00      1.00        29

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60



## 🟧 2. MultinomialNB — Dades de recompte (ideal per text)
Les característiques han de ser no-negatives (counts, TF-IDF).

In [2]:
# Dataset de recompte
X_mult = np.array([
    [3,0,1],  # classe 0
    [4,1,0],
    [0,2,4],  # classe 1
    [1,3,3]
])
y_mult = np.array([0,0,1,1])

m_model = MultinomialNB()
m_model.fit(X_mult, y_mult)
pred = m_model.predict(X_mult)
print('== MultinomialNB ==')
print(confusion_matrix(y_mult, pred))
print(classification_report(y_mult, pred))

== MultinomialNB ==
[[2 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



## 🟩 3. BernoulliNB — Característiques binàries (0/1)
Ideal per presència/absència.

In [3]:
# Dataset binari
X_bin = np.array([
    [1,0,1],
    [1,1,0],
    [0,1,1],
    [0,0,1]
])
y_bin = np.array([1,1,0,0])

b_model = BernoulliNB()
b_model.fit(X_bin, y_bin)
pred = b_model.predict(X_bin)
print('== BernoulliNB ==')
print(confusion_matrix(y_bin, pred))
print(classification_report(y_bin, pred))

== BernoulliNB ==
[[2 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



## 🟪 4. CategoricalNB — Dades categòriques discretes
Per atributs com 'nivell educatiu', 'color', etc.

In [4]:
# Dataset categòric
X_cat = np.array([
    [0,1],
    [1,1],
    [2,0],
    [1,0]
])
y_cat = np.array([0,0,1,1])

c_model = CategoricalNB()
c_model.fit(X_cat, y_cat)
pred = c_model.predict(X_cat)
print('== CategoricalNB ==')
print(confusion_matrix(y_cat, pred))
print(classification_report(y_cat, pred))

== CategoricalNB ==
[[2 0]
 [0 2]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         2

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4

